param(
    [ValidateSet("Install", "Uninstall")]
    [string]$Action = "Install",
    [double]$Speed = 10.0,
    [string]$TargetProcess = "isaac-ng.exe",
    [int]$ScanIntervalMs = 1000,
    [string]$CheatEngineDir = "C:\Program Files\Cheat Engine",
    [switch]$LaunchCheatEngine
)

$ErrorActionPreference = "Stop"

function Escape-LuaString {
    param([string]$Value)
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$watchScriptPath = (Resolve-Path (Join-Path $scriptDir "ce_speedhack_watch.lua")).Path
$autorunDir = Join-Path $CheatEngineDir "autorun\custom"
$autorunFile = Join-Path $autorunDir "isaac_speedhack_autorun.lua"
$ceExe = Join-Path $CheatEngineDir "cheatengine-x86_64.exe"

if ($Action -eq "Uninstall") {
    if (Test-Path $autorunFile) {
        Remove-Item $autorunFile -Force
        Write-Host "Removed autorun script: $autorunFile"
    } else {
        Write-Host "Autorun script not found: $autorunFile"
    }
    return
}

if (-not (Test-Path $CheatEngineDir)) {
    throw "Cheat Engine directory not found: $CheatEngineDir"
}

if (-not (Test-Path $watchScriptPath)) {
    throw "Watch script not found: $watchScriptPath"
}

if (-not (Test-Path $autorunDir)) {
    New-Item -ItemType Directory -Path $autorunDir -Force | Out-Null
}

$luaTarget = Escape-LuaString -Value $TargetProcess
$luaWatchScriptPath = Escape-LuaString -Value $watchScriptPath

$lua = @"
-- Auto-generated by scripts/install_ce_speedhack_watch.ps1
ISAAC_SPEEDHACK_TARGET = "$luaTarget"
ISAAC_SPEEDHACK_SPEED = $Speed
ISAAC_SPEEDHACK_SCAN_MS = $ScanIntervalMs
dofile("$luaWatchScriptPath")
"@

Set-Content -Path $autorunFile -Value $lua -Encoding ASCII
Write-Host "Installed autorun script: $autorunFile"
Write-Host "Configured target=$TargetProcess speed=${Speed}x scan=${ScanIntervalMs}ms"

if ($LaunchCheatEngine) {
    if (Test-Path $ceExe) {
        Start-Process -FilePath $ceExe | Out-Null
        Write-Host "Launched: $ceExe"
    } else {
        Write-Warning "Cheat Engine executable not found: $ceExe"
    }
}
